### ISSUE TITLE
GNB comp

### ISSUE THREAD

**Issue by hyobiin9** [FS2-Part4-Team3/2-Moving-3-FE#4]
### Logged Out - PC
![image](https://github.com/user-attachments/assets/a1cf61b5-0bfd-4fb9-8c76-07d0282a0cf6)
### Logged Out - Tablet/Mobile
![image](https://github.com/user-attachments/assets/03bcad17-c84a-48a8-ab2a-cb92150ad949)

### Logged Out Menu - Tablet/Mobile
![image](https://github.com/user-attachments/assets/3ec0b123-9038-426e-ab84-33be3223122b)

### Logged In - PC
![image](https://github.com/user-attachments/assets/a2c92dc4-4728-4806-8b06-a8caa6d4c297)
### Logged In - Tablet/Mobile
![image](https://github.com/user-attachments/assets/51f25ab5-638b-4070-bc7c-0a43d31d944c)

### Logged In Menu - Tablet/Mobile
![image](https://github.com/user-attachments/assets/013a9eca-5907-409d-aced-6dfaeea90786)

## TO-DO

- [x] 로그아웃 pc nav 구현
- [x] 로그아웃 tablet nav 구현
- [x] 로그아웃 tablet nav menu 구현
- [x] 로그인 pc nav 구현
- [x] 로그인 talet nav 구현
- [x] 로그인 tablet nav menu 구현

## 기타
프로필 모달은 추후 제작하겠습니다.
